### PR TITLE
Use react-router-config

### PR DESCRIPTION
**Pull request by otaviosoares**
Following the suggestions of https://github.com/jaredpalmer/after.js/pull/173#issuecomment-427312959 and https://github.com/jaredpalmer/after.js/pull/173#issuecomment-431709565

This is a first attempt of supporting nested routes by using react-router-component.

I'd love to hear some feedback. There is a known problem, it only injects the data for the last component (nested). I thought about creating a function ```renderRoutes``` that injects the data based on the path, so we could use that instead of react-router-config`s renderRoutes in the root components.

Please, let me know your thoughts.

Usage example:

```js
// routes.js
import React from 'react';

import { asyncComponent } from '@jaredpalmer/after';

export default [
  {
    path: '/',
    exact: true,
    component: asyncComponent({
      loader: () => import('./Home'),
      Placeholder: () => <div>...LOADING...</div>,
    })
  },
  {
    path: '/root',
    component: asyncComponent({
      loader: () => import('./Root'),
      Placeholder: () => <div>...LOADING...</div>,
    }),
    routes: [{
      path: '/root/nested',
      exact: true,
      component: asyncComponent({
        loader: () => import('./Nested'),
        Placeholder: () => <div>...LOADING...</div>,
      })
    }]
  }
];
```

```js
// Root.js
import React from 'react'
import { renderRoutes } from 'react-router-config';

class Root extends React.Component {
  static async getInitialProps() {
    return { rootData: 'cool!' }
  }
  render() {
    const { route: { routes }, rootData } = this.props
    return (
      <div>
        <h1>Root - {rootData}</h1>
        {/* rootData is undefined */}
        {renderRoutes(routes)}
      </div>
    )
  }
}

export default Root
```

```js
// Nested.js
import React from 'react'

class Nested extends React.Component {
  static async getInitialProps() {
    return { nestedData: 'neat!' };
  }

  render() {
    const { nestedData } = this.props
    return (
      <div>
        <h2>Nested - {nestedData}</h2>
      </div>
    )
  }
}

export default Nested
```

Thanks

### CODE REVIEW

**Comment by aaronfordnet** [comment]
Looks good. It would be great to see this move forward.

**Comment by jaredpalmer** [comment]
Reviewing now

**Comment by jaredpalmer** [comment]
I put the comment on the wrong PR. 

See this: https://github.com/jaredpalmer/after.js/pull/173#issuecomment-469686859

**Comment by jaredpalmer** [comment]
I think this PR is on the right track. My hot take is that we should leverage `react-router-config` so that you can write a route tree like this:

> Note that `<App>` is the layout component we've been describing.

```tsx
import React from 'react';

import { asyncComponent } from '../asyncComponent';
import NonDymamicImport from './components/NonDynamicExport';
import { NoGetInitialProps } from './components/NoGetInitialProps';
import { App } from './components/App';

const Placeholder = () => <div>...LOADING...</div>;

export default [
  {
    path: '/',
    component: App,
    routes: [
      {
        path: '/',
        exact: true,
        component: asyncComponent({
          loader: () => import('./components/Home'),
          Placeholder,
        }),
      },
      {
        path: '/async-get-initial-props',
        exact: true,
        component: asyncComponent({
          loader: () => import('./components/AsyncGetInitialProps'),
          Placeholder,
        }),
      },
      {
        path: '/non-dynamic-import',
        exact: true,
        component: NonDymamicImport,
      },
      {
        path: '/non-default-export',
        exact: true,
        component: asyncComponent({
          loader: () =>
            import('./components/NoNDefaultExport').then(
              module => module.NonDefaultExport
            ),
          Placeholder,
        }),
      },
      {
        path: '/no-get-initial-props',
        exact: true,
        component: NoGetInitialProps,
      },
      {
        path: '/route',
        component: asyncComponent({
          loader: () => import('./components/RootRoute'),
          Placeholder,
        }),
        routes: [
          {
            path: '/route/nested',
            component: asyncComponent({
              loader: () => import('./components/NestedRoute'),
              Placeholder,
            }),
          },
        ],
      },
    ],
  },
];
```

`<App/>` is a layout component that must render the after party (i.e. where the data state is kept). This is the place for creating isomorphic, non-data context providers (e.g. react-helmet, react-gateway, etc.)

```tsx
import * as React from 'react';
import { renderRoutes, RouteConfigComponentProps } from 'react-router-config';
import { Helmet } from 'react-helmet'

export interface AppProps extends RouteConfigComponentProps<{}> {}

export interface AppState {}

export class App extends React.Component<AppProps, AppState> {
  render() {
    const { route, ...rest } = this.props;
    // route.route moves us into the children of the layout component for data fetching purposes
    return <>
              <Helmet titleTemplate="%s -Jared Palmer">           
                <meta property="og:site_name" content="Jared Palmer" />
                <meta name="og:url" content="..." />
                <meta name="og:image" content="/me.jpg" />
                <meta name="twitter:card" content="summary" />
                <meta name="twitter:url" content={url} />
                <meta name="twitter:site" content="@jaredpalmer" />
                <meta name="twitter:image" content="/me.jpg" />              
              </Helmet>
              <After routes={route.route} {...rest} />             
         </>;
  }
}
```

We may want to extend some helper callbacks for stuff like route changes out of the `<After>` component. This could be useful for analytics.

With this, we should simplify the code in render. We can also make the constraint that the layout component (i.e. `<App>` cannot be lazily loaded (since it is always rendered) anyways.

**Comment by shaodahong** [comment]
that's good, and we should be support like `<Redirect to="/" />` route config

**Comment by shaodahong** [comment]
@otaviosoares have some question, not found child route `getInitialProps ` exec

**Comment by fugalfunkster** [comment]
I'd also like to see this move forward! Are there any loose ends that need tying up?

**Comment by rickihastings** [comment]
Any news on this? This would make this library 10x more attractive.

**Comment by MrLoh** [comment]
not stale

**Comment by otaviosoares** [comment]
Sorry, I didn't have time to look back at this. Planning to do it this week.

**Comment by nimaa77** [comment]
@otaviosoares any updates on this? is there anything that I can help with?

**Comment by nimaa77** [comment]
😪 any updates on this? @otaviosoares

**Comment by otaviosoares** [comment]
I want to actively work on this again. @nimaa77 I saw you also worked on something similar. Would you like to build it together ? Maybe already using react-router 6.

**Comment by nimaa77** [comment]
that's great!
I tried to do it but I was unable to implement it in the right way :)

**Comment by otaviosoares** [comment]
@nimaa77 do you mind sharing which problems you faced?

**Comment by nimaa77** [comment]
I can't remember all of them but this is what I can remember right now:

1) about `getInitilaProps`

imagine with having a route config like this:
```js
const routes = [
  {
    path: "/",
    component: App,
    routes: [
      {
         path: '/',
         exact: true,
         component: Home,
      },
      {
         path: "/foo",
         component: Foo,
         routes: [
            {
               path: "/foo/1",
               component: Nested1
            },
            {
               path: "/foo/2",
               component: Nested2
            }
         ]
      },
    ]
  }
]
```

so if the user opens `/foo/1` we call `Foo.getInitilaProps` and `Nested1.getInitilaProps` and we wait for promises to resolve and we inject the result to the component as a prop and ...

then if that user moves from `/foo/1` to `/foo/2`, should we call `Foo.getInitilaProps` again or not!!?

2) order of calling the `getInitialProps`
should we first call `Nested1.getInitilaProps` and then `Foo.getInitilaProps` or we are going to call them at the same time

What if `Nested1.getInitilaProps` return `{ redirectTo: "/foo" }` from `getInitilaProps` and `Foo.getInitilaProps` return `{ redirectTo: "/bar" }` we should redirect to which one?


3) how we should pass the data from getInitialProps to the components?

right now we are calling the `loadInitialData` method in `<After />` (which calls the matched component `getInitialProps`) and then we pass the data to the component in the `render` method ...

when we use nested routes we can't pass the data directly to the nested component, we should save the result of the `getInitlaProps` into a context and we read the data from context and inject it to the nested component

but if we put all the data that comes from `getInitlaProps` in one context, how we are going to determine which data belongs to which component!??

**Comment by nimaa77** [comment]
@otaviosoares and could you please open a new pull request, so we all the discussions in one place?

**Pull request closed without merging**
