### PR TITLE
WIP: Feature - Nested Routes

### PR DESCRIPTION
**Pull request by nimaa77**
Add nested routes to After.js using [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config) package. since [React Router 6](https://github.com/ReactTraining/react-router/blob/dev/docs/installation/getting-started.md) is on the way (and nested routes are going to be a thing in this version)

we are taking notes from this comment https://github.com/jaredpalmer/after.js/pull/208#issuecomment-469847894

### TODO:
- [ ] don't call getInitalProps on the parent when user moves from one nested route to another one 
- [ ] save the result of getInitalProps inside an array or object
- [ ] create a context so the component can read getInitalProps result without prop drilling 
- [ ] create a function that reads data from context and passes data to `renderRoutes()`

### Breaking Changes
There are some breaking changes (I will update this when everything is done...)

### CODE REVIEW

**Comment by nimaa77** [comment]
I will explain this later

```js
function comparer(otherArray){
  return function(current){
    return otherArray.filter(function(other){
      return other.path == current.path && other.match.url == current.match.url
    }).length == 0;
  }
}

const matched = currentBranches.filter(comparer(prevBranches));
```

**Comment by jwkellyiii** [comment]
I see v2.0.0-1 is out, is the plan for this this PR to eventually make it to 2.0.0?

**Comment by anasbud** [comment]
Any update on this PR ?

**Comment by nimaa77** [comment]
ok sorry for being late
it's very hard to handle it with `react-router-config` and there are many edge cases that react-router-config can't handle
 

so I'm waiting for react-router v6 (trust me it has a nice API for nested routes)

**Pull request closed without merging**
