### PR TITLE
RR v5 bug + fallback async support

### PR DESCRIPTION
**Pull request by chaffeqa**
Addresses x2 issues:
1. React-Router v5 introduced a bug where `matchPath` will throw an error if no `path` property is on the route.
2. If using a "fallback' (not-found) route, the route would not support async loading / `getInitialProps` in the previous implementation

**EDIT**: in testing I became aware that this was also causing errors in the `ensureReady` function.  Instead of just fixing it i moved some of the logic to be shared.
In addition, I fixed a point of confusion: `routes.find` will only invoke the first `Promise`, so there would only be x1 Promise ever to resolve (even though the typings said there could be multiple).
Finally, I also added `TRouteData` to help reason about the `getInitialProps` response and how that is passed down.  It helped me reason on where I can access it and where it's not yet "resolved"

### CODE REVIEW

**Comment by vspedr** [comment]
Hi @chaffeqa, do you have a working example using this change? I could not get it to work after upgrading to RR v5, it still throws the same error reported in #209.

If there is something I can do to help investigating, please let me know!

**Comment by chaffeqa** [comment]
Unfortunately we use a forked version to power https://picks.nba.com (since we wanted to do a little more options for component mounting until `getInitialProps` has completed).  This is mostly a backport from that version.

If you have an example I could check and debug, I'd love to try to figure out that error.

**Comment by jaredpalmer** [comment]
@chaffeqa want to pick this back up?

**Comment by dimensi** [comment]
Any news?

**Comment by mbmohib** [comment]
Is there any chance to resolve it soon?

**Comment by chaffeqa** [comment]
Sorry been a busy time for us, I may have some time to look deeper into how to move this forward.  If anyone else could test it in their apps that would be super, otherwise I'm hoping at some point to figure out how to prove this out more.

AFAIK there is nothing wrong with this implementation, but like I said, its hard for me to validate since our version is still the forked version

**Comment by nimaa77** [comment]
Hi, the first issue that was about throwing an error just fixed in [react-router-dom v5.0.1](https://github.com/ReactTraining/react-router/commit/7bd1407803ba8fbec8283f12a27128b8bd4bde75) so it won't throw errors anymore, `matchPath` will return null if the given `path` is undefined.
but we may want to add support for it in `after.js`!

last week I was working on #237 and I had a problem with the react-router matchPath.
it works differently than `<Swtich>` and `<Route>` components. if we render a `<Route>` without a path property `<Route component={NotFound} />` internally will receive `path: "/"` from `<Router>` context.

[`<Router>` Line 60](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Router.js#L60)
[`<Switch>` Line 35 also check line 31](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L35)
[`<Route>` Line 39](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L39)

What I did to fix it:
```jsx
// loadInitialProps.tsx

export async function loadInitialProps(routes: AsyncRouteProps[], pathname: string, ctx: CtxBase): Promise<InitialProps> {
  const promises: Promise<any>[] = [];

  const matchedComponent = routes.find((route: RouteProps) => {

    // matchPath dont't accept undifined path property
    // in <Switch> componet Child <Route> default path value is an empty string
    const match = matchPath(pathname, {...route, path: route.path || ""});
    ...
```
[loadInitialProps.tsx](https://github.com/nimaa77/after.js/blob/feature/assets/src/loadInitialProps.tsx#L13)

**Comment by chaffeqa** [comment]
Hmmm intiresting, thanks for reporting this! I was actually just looking at your PR and wondering how much overlap it had with this one.

I just checked the code in this PR based on what you said above @nimaa77 and it looks like this:

```typescript
  const matchedRoute = routes.find(
    (route) => !!route.hasOwnProperty("path") && !!matchPath(pathname, route)
  ) || routes.find(
    // if no route is found, attempt to find a fallback (not-found) route
    (route) => !route.hasOwnProperty("path")
  )
  // if this is the fallback (not-found) route, `matchPath` errors out if there is no `path`, so we use "*"
  const match = matchedRoute && matchPath(pathname, matchedRoute.hasOwnProperty("path") ? matchedRoute : { path: "**" }) || undefined
```

I think I could change that to:

```typescript
const match = matchedRoute && matchPath(pathname, { ...matchedRoute, path: matchedRoute.path || "*" }) || undefined
```

I don't recall why I preferred `"**"` to `"*"` honestly, I think it was because it matches deep 404's (`/404` would match `"*"` but not `/deep/404`?)

Let me know if my logic was wrong there, otherwise happy to see if I can work some of these items into #237 (I don't know how much they overlap / are compatible?)

**Pull request closed without merging**
