### PR TITLE
[feature]: Transition Behavior

### LINKED ISSUE #340: Add transitionBehavior prop so we can show loading state when getInitialProps is fetching data
Please provide a way to revert behaviour of `getInitialProps` previous to https://github.com/jaredpalmer/after.js/pull/251 and how @jaredpalmer originally implemented.

As @dbbk had commented:
> I prefer to instantly transition and display skeleton screens, keeping the user on the old screen makes our app feel slow and unresponsive.

Strongly agree on this. Many of the projects depend on this flow and not the new flow (which might be useful for few only).

Please take Twitter as an example for proper routing.

### PR DESCRIPTION
**Pull request by nimaa77**
### new transitionBehavior prop on `<After />`

```js
transitionBehavior: instant | blocked
```
the default for value for `transitionBehavior` prop is `blocked` (we can also change the default to `instant` but it's going to be a breaking change)

blocked behavior (default):

`navigation event occurs` -> `wait until getInitailProps get finished` -> `render the next page with injected props (I mean results of the getInitailProps)`

blocked

instant behavior:
`navigation event occurs` -> `call getInitailProps` -> `render the next page` -> `re-render component when getInitailProps is finished with injected props`

instant

### TODO
- [x] have a discussion about `scrollToTop` behavior
- [x] have a discussion about new `isLoading` prop 
- [x] better README.md (I'm not a native speaker so it may have grammar issues)
- [ ] add some tests
 
### Discussion
I need feedback :)

#### When we should scroll to top (in `instant` mode)
before #251 it scrolls to top when `getInitailProps` is finished
right now it's the same too

but as you may already notice in the second gif when we click on an item, data on the screen gets removed, and then we show the loading state. by removing the data from the screen footer and content under the data (matched `<Page />`) will jump up and the user will see the footer...

I think it's better to scroll to the top at the same time that we showing the loading state

```js
// current behavior
cont data = await getInitialProps()
  .then((result) => {
     scrollToTop();
     return result;
  })

// my sugestion
scrollToTop();
const data = await getInitialProps();
```

#### How we understand if getInitialProps is in the loading state

I can remember before #251 I always checked and see if the result of `getInitialProps` is undefined or not 
but we can do better than that maybe we inject a new prop (e.g: `isLoading`) to the components

this `isLoading` is also useful in `blocked` mode (e.g: using `ngprogress`)

### How we can test this?

```bash
yarn add @jaredpalmer/after@3.0.3-canary.0
```

or if you are using npm:

```bash
npm i @jaredpalmer/after@3.0.3-canary.0
```

### Breaking Changes 
nothing 🎉 

closes #340

### CODE REVIEW

**Comment by dbbk** [comment]
I think it makes sense to scroll to top immediately in instant mode, as the user would expect to see the above-the-fold loading state (ie a skeleton screen). I can’t think of a reason why you’d want it to remain lower until the data is loaded.

**Comment by nimaa77** [comment]
yeap, it makes sense to scroll to top immediately

and what about `isLoading` prop?

**Comment by nimaa77** [comment]
for loading state I'm thinking about something like this too 

```js
<After 
  routes={routes}
  data={data}
  onStartFetching={() => doSomeThing()}
  onFinishFetching={() => doSomeThingElse()}
/>
```

(maybe it's better to create another issue and discuss about loading thing on that issue)

**Comment by atulmy** [comment]
Thanks @nimaa77 for this! 

> have a discussion about scrollToTop behavior

As @dbbk mentioned, scroll to top immediately in instant mode would be ideal.

> have a discussion about new isLoading prop

`isLoading` is definitely nice to have. Will simplify the data fetching implementation in user-land.

Looking forward to the merge and shipping this fix in production! 🚀

**Comment by atulmy** [comment]
Hey @nimaa77, are you planning to release this into master anytime soon? `isLoading` support would also help.

**Comment by atulmy** [comment]
@nimaa77, In the current implementation, whenever there is change in the route, we receive the old props and then new props once the promise has been resolved. 

Original implementation used to reset the props to either null or whatever is set before the promise. Hope we can revert this behaviour as well and also provide `isLoading` just to make it easier.

**Comment by jwrlee88** [comment]
How would the `isLoading` prop be used? Would it be something available in getInitialProps? How would we go about using the prop to conditionally render different states of the page? For example, could I do something like:

```
class Example extends React.Component {
    static async getInitialProps({isLoading, store, req}) {
        if(isLoading){
             return { props: isLoading, some: OtherProps}
        } else {
            return { pageProps }
        }
    }

   render() {
      if(!pageProps) {
          return <LoadingScreen/>
      }

     return (
         <div>{something with pageProps}</div>
     )
   }
}
```
Or would it be a variable that we could manipulate? so that we could set the isLoading prop to true/false depending on the status of our API call that we're `awaiting` on?

```
class Example extends React.Component {
    static async getInitialProps({isLoading, store, req}) {
       isLoading = true
       const result = await myAPICall();
       isLoading = false;

       return {result, isLoading}
    }

   render() {
      if(!isLoading) {
          return <LoadingScreen/>
      }

     return (
         <div>{something with result}</div>
     )
   }
}
```

Maybe some sort of a use case explaining how one would go about using the isLoading props in `getInitialProps` would be helpful to get more feedback. :slightly_smiling_face:

**Comment by nimaa77** [comment]
> @nimaa77, In the current implementation, whenever there is change in the route, we receive the old props and then new props once the promise has been resolved.
> 
> Original implementation used to reset the props to either null or whatever is set before the promise. Hope we can revert this behaviour as well and also provide `isLoading` just to make it easier.
> 
> When user navigates from `example.com/dw-english` to `example.com/euronews-english`, this is how it looks:
> Screenshot 2020-06-02 at 5 54 56 PM

oh my bad, I'm going set the data prop to `null`

**Comment by nimaa77** [comment]
> How would the `isLoading` prop be used? Would it be something available in getInitialProps? How would we go about using the prop to conditionally render different states of the page? For example, could I do something like:
> 
> ```
> class Example extends React.Component {
>     static async getInitialProps({isLoading, store, req}) {
>         if(isLoading){
>              return { props: isLoading, some: OtherProps}
>         } else {
>             return { pageProps }
>         }
>     }
> 
>    render() {
>       if(!pageProps) {
>           return <LoadingScreen/>
>       }
> 
>      return (
>          <div>{something with pageProps}</div>
>      )
>    }
> }
> ```
> 
> Or would it be a variable that we could manipulate? so that we could set the isLoading prop to true/false depending on the status of our API call that we're `awaiting` on?
> 
> ```
> class Example extends React.Component {
>     static async getInitialProps({isLoading, store, req}) {
>        isLoading = true
>        const result = await myAPICall();
>        isLoading = false;
> 
>        return {result, isLoading}
>     }
> 
>    render() {
>       if(!isLoading) {
>           return <LoadingScreen/>
>       }
> 
>      return (
>          <div>{something with result}</div>
>      )
>    }
> }
> ```
> 
> Maybe some sort of a use case explaining how one would go about using the isLoading props in `getInitialProps` would be helpful to get more feedback. 🙂

no, it's a prop that gets injected to the component
it's get controlled by `after.js` so whenever it calls `getInitialProps` => `isLoading` = `true`
and when the promise that comes from `getInitialProps` gets `resolved` or `rejected`, `isLoading` is going to be `false`

**Comment by jwrlee88** [comment]
> no, it's a prop that gets injected to the component
it's controlled by after.js so whenever it calls getInitialProps => isLoading = true
and when the promise that comes from getInitialProps gets resolved or rejected, isLoading is going to be false

That sounds like a very useful feature then! :slightly_smiling_face:

**Comment by atulmy** [comment]
Hey @nimaa77, are you planning to release this into master anytime soon?

**Comment by nimaa77** [comment]
yes, I will release this today.
I was a little sick and busy for a while but I'm fine now

**Comment by pmbednarczyk** [comment]
hey @nimaa77 
first of all, thank you for your great job!

I have a question. I use `transitionBehavior` `instant` and it **works as expected on my dev build**. 
I mean i get proper `props.isLoading` value in component and my `<Loader />` component is visibile while switching pages.

Code:
```const HomePageContainer = (props) => {
  console.log('HomePageContainer', props.isLoading);
  if (props.isLoading) {
    return <Loader isFullscreen />;
  }
  return <HomePage {...props} />;
};

const mapStateToProps = ({ post: { getPostListReducer }, symptom: { getSymptomListReducer } }) => ({
  postListData: getPostListReducer?.data,
  symptomListData: getSymptomListReducer?.data,
});
```

But **on production build it doesn't work** anymore (no loader visible). 

I attach videos to show it (dev and prod build - same path):

dev build: https://drive.google.com/file/d/1W-UKD48NOTgX-p6NhXm0S64W8qMyTucE/view?usp=sharing, 

prod build: https://drive.google.com/file/d/1pD9JjmM4qqDABE9myB0rZxHiFzAQfqbQ/view?usp=sharing

Do you have any idea how can I fix it?

**Comment by nimaa77** [comment]
@pmbednarczyk could you please create an issue for this and an example that reproduces this?
it's little hard to guess what could be wrong

**Comment by pmbednarczyk** [comment]
Ok... I know the reason <facepalm>.
After few days of debugging I finally decided to upgrade Razzle to 4.X and it solved the problem hehe =D

**Pull request merged**
