### PR TITLE
Enable Tree-shaking and add ESM Build

### PR DESCRIPTION
**Pull request by nimaa77**
After.js doesn't support Tree-shaking, this causes `render.js`, and `Document.js` get inside the client (browser) bundle.

Anyone who uses `after.js` can save about 60KB easily (in 2 seconds).

`render.js` includes `ReactDomServer` and webpack nodejs for browser runtime, and it's packed inside the client bundle

image

Document.js 3.61KB
render.js 3.58KB
reactdom-server.browser.production.min.js 18.77KB (this is ReactDom.RenderToString that works in browser, and it's in bundle because of `render.js` file)
Url.js 7.53KB
punnycode.js, react-side-effect.js, querystring-es3.js, ...

**total: 57.29KB**

## Desired Behavior
to not include unnecessary packages and save about 60KB 

image

---
Also, there was a problem with `ensureReady.js`and `render.js` files, in which the default exported module was not correct.

Before:
```js
module.exports = require('./build/cjs/ensureReady');
```

After:
```js
module.exports = require('./build/cjs/ensureReady').ensureReady;
```

with the above changes, users can use safely use `babel-plugin-transform-imports` in situations that build system is not able to handle es modules.

### Breaking Changes
There is no breaking change 🎉

### CODE REVIEW

**Comment by nimaa77** [comment]
fixes #238

**Comment by nimaa77** [comment]
and heavily needed by #237 since in `getAssets.ts` file uses `razzle-dev-utils/logger` module and it contains other modules for print logs in console and color module ... 

these things have nothing to do with browser

**Comment by jaredpalmer** [comment]
Use tsdx plz

**Comment by nimaa77** [comment]
@jaredpalmer I've switched to tsdx but tree-shaking is not working.

can you take look and see what's wrong with this setup?

**Comment by jaredpalmer** [comment]
Headed to Austria will not get to it til next week.

**Comment by nimaa77** [comment]
have a nice trip 😎.
handle it in the old school way for now.
I will push this PR to [esm-build](https://github.com/jaredpalmer/after.js/tree/esm-build) branch.

**Comment by nimaa77** [comment]
closing this, for now. I will open another Merge Request later this week ...

**Pull request closed without merging**
