### PR TITLE
<AfterScripts />, <AfterStyles />

### PR DESCRIPTION
**Pull request by nimaa77**
Add Two New Component (AfterScripts, AfterStyles) useful for `customDocument` component.
`<AfterData />` data prop is optional now. (if no prop passed it will use `data` that passed to `getInitialProps`)

from:
```js
import React from 'react';
import { AfterRoot, AfterData } from '@jaredpalmer/after';

class Document extends React.Component {
  static async getInitialProps({ assets, data, renderPage }) {
    const page = await renderPage();
    return { assets, data, ...page };
  }

  render() {
    const { helmet, assets, data } = this.props;

    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();

    return (
      <html {...htmlAttrs}>
        <head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet="utf-8" />
          <title>Welcome to the Afterparty</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {helmet.title.toComponent()}
          {helmet.meta.toComponent()}
          {helmet.link.toComponent()}
          {assets.client.css && (
            <link rel="stylesheet" href={assets.client.css} />
          )}
        </head>
        <body {...bodyAttrs}>
          <AfterRoot />
          <AfterData data={data} />
          <script
            type="text/javascript"
            src={assets.client.js}
            defer
            crossOrigin="anonymous"
          />
        </body>
      </html>
    );
  }
}
```
to:

```js
import React from 'react';
import { AfterScripts, AfterStyles, AfterRoot, AfterData } from "@jaredpalmer/after"

class Document extends React.Component {
  static async getInitialProps({ renderPage }) {
    const page = await renderPage();

    return { ...page };
  }

  render() {
    const { helmet } = this.props;
    // get attributes from React Helmet
    const htmlAttrs = helmet.htmlAttributes.toComponent();
    const bodyAttrs = helmet.bodyAttributes.toComponent();

    return (
      <html {...htmlAttrs}>
        <head>
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta charSet="utf-8" />
          <title>Welcome to the Afterparty</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {helmet.title.toComponent()}
          {helmet.meta.toComponent()}
          {helmet.link.toComponent()}
          <AfterStyles />
        </head>
        <body {...bodyAttrs}>
          <AfterRoot />
          <AfterData />
          <AfterScripts />
        </body>
      </html>
    );
  }
}
```
no props needed (with help of context 😄)

`__AfterContext` (`import { __AfterContext } from "@jaredpalmer/after"`) contains all props that passed to Document component, so Developers can use it to build their clean customDocuments

This can help migration easier for #237 ([Check Migration Guide](https://github.com/nimaa77/after.js/blob/feature/assets/UPGRADING.md#update-documentjs-only-if-you-used-custom-document))

### Breaking Changes
🎉 nothing

the minimum React version is now 16.3 because we are using React Context.

### CODE REVIEW

**Comment by psobhanlo** [comment]
@nimaa77  awesome    ,

**Comment by HosseinShabani** [comment]
Nice

**Comment by jaredpalmer** [comment]
npm token added! @nimaa77

**Comment by jaredpalmer** [comment]
The token is on a special-purposed npm account just for afterjs 😉

**Pull request merged**
