### PR TITLE
Dynamic 404 and Redirects

### PR DESCRIPTION
**Pull request by nimaa77**
with this, we can show 404 Pages based on API response inside getInitialProps function.
we can also handle authorization from getInitialProps.

for showing 404 component just return `{ statusCode: 404 }` and for redirect return `{ redirectTo: "/new-location", /* statusCode is optional default value is 301  */, statusCode: 302 }` from getInitialProps.

updated readme file and added new tests to cover new features. I wanted to write more tests but I can not use react-testing-library because of typescript version (react-testing-library used some library that is based on TypeScript V3 and `unknown` type was not available for it).

### CODE REVIEW

**Comment by gobengo** [comment]
@jaredpalmer Can we have this?

**Comment by jaredpalmer** [comment]
bitmoji

**Comment by gobengo** [comment]
@jaredpalmer Thanks comrade. lit indeed 🙏

**Comment by nimaa77** [comment]
Wooow Nice :dancer:, I'm going to have a merge party after this.

I have one more awesome thing to show check this #232

**Pull request merged**
