### PR TITLE
with-redux-example

### PR DESCRIPTION
**Pull request by mohammad-amin-hesam**
Hello.
this is a complete example that shows how after.js works with redux.

plz check it thx :)

### CODE REVIEW

**Comment by Superoryco** [comment]
Hi, just wondering is it really necessary to pass 'store' as extra render option?
https://github.com/mohammad-amin-hesam/after.js/blob/feff9b90e762961feecd273368ab0250a487c1b1/examples/with-redux/src/server.js#L37

**Comment by nimaa77** [comment]
maybe you want to dispatch something into the redux store, or you want to read something from the redux store and conditionally fetch some data in `getInitialProps`!

so you can dispatch into the store with `store.dispatch()` and you can read from store with `store.getState()`

**Comment by Superoryco** [comment]
@nimaa77 got it! Thank you. I notice this point cause of the typescript warning,  is there any way I can extend AfterRenderOptions interface to cross the warning? I know it is more like a typescript problem...

**Comment by nimaa77** [comment]
simply use `// @ts-ignore` in server.js, and in your component `getInitialProps` specify a type for the first param and declare store in that type.

**Pull request closed without merging**
