### PR TITLE
From and To sections are mixed up

### PR DESCRIPTION
**Pull request by stikhomirov**

### CODE REVIEW

**Comment by nimaa77** [comment]
no, it's ok right now

**Comment by stikhomirov** [comment]
Please, review the last section concerning custom Document of upgrade file again.
In "From" block supposed to be the previous version of Document example. But there is no AfterScripts and AfterStyles in import at the top though they should have been removed only after update to the last version of after.js. And vice versa, they are present in "TO" section as long as other changes.

**Comment by stikhomirov** [comment]
Only Document part, the others are good.

**Comment by nimaa77** [comment]
this is how it should look like

https://github.com/jaredpalmer/after.js/blob/master/examples/layout-component/src/Document.js

so it's correct

**Comment by stikhomirov** [comment]
Sorry for insisting, the problem looks more complex that I thought.
Readme file, upgrade.md file and Document.js files in all examples are outdated.
As a proof, look at the date Document.js was modified.
Each Document.js file must have been modified in new version, but only server.js files are updated.
Please, double check it. At least, Document part of readme file wasn't changed, but according to upgrading.md it should have been.
The last arguement is that I'am using custom renderer in my project and after upgrade I was to update my custom Document.js file to "FROM" version from Upgrading.md file in order to make my project work.

**Comment by nimaa77** [comment]
I can't find anything wrong with README.md and examples 

can you send me the link for those files

and what's your problem with Document.js, it throws an error message? or what?

**Comment by stikhomirov** [comment]
My point is that according to instructions in Upgrading.md file not only server.js but also Document.js must be updated to new version. [https://github.com/jaredpalmer/after.js/blob/master/UPGRADING.md#update-documentjs-only-if-you-used-custom-document](https://github.com/jaredpalmer/after.js/blob/master/UPGRADING.md#update-documentjs-only-if-you-used-custom-document)
 But none of Document.js files in any example was updated. While the last commit in server.js file  is "Update examples for new version" all other files are initially added 4 months ago. Look at component-layout-example for example. https://github.com/jaredpalmer/after.js/tree/master/examples/layout-component/src
Screenshot afterjs
Unfortunately, I can't remember the last error I got, because I had a bunch of them during upgrade, and until I followed all instructions in Upgrading.md file I could get my project to work.

**Comment by nimaa77** [comment]
all of them are updated :)

in version 1.5 https://github.com/jaredpalmer/after.js/releases/tag/v1.5.0
we introduced 2 new Components: AfterScripts, AfterStyles

and all examples get updated at that time...

**Comment by stikhomirov** [comment]
My bad, sorry, I added Document (of version 1.5 obviously) while I was using version 1 of after.js. And it did work! ;) That's why I was confused then about upgrading as Document.js version was already updated. (and previous version did work too!)
Sorry again for bothering you with this. You guys, are doing a great job!

**Pull request closed without merging**
